# Generated by Django 3.1.7 on 2021-03-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(choices=[('szt', 'sztuk'), ('g', 'gram'), ('kg', 'kilogramów'), ('ml', 'mililitrów'), ('l', 'litrów')], default='szt', max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
        ),
    ]
