# Generated by Django 3.1.7 on 2021-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('szt', 'sztuk'), ('g', 'gram'), ('kg', 'kilogramów'), ('ml', 'mililitrów'), ('l', 'litrów')], default='szt', max_length=3),
        ),
    ]
